apiVersion: v1
kind: Service
metadata:
  namespace: log-apps
  name: ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
