apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: todo-namespace
  name: daily-todo
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-todo
            image: thesamsai/daily-todo:v2
          restartPolicy: OnFailure
