apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: todo-namespace
  name: daily-todo
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-todo
            image: thesamsai/daily-todo:v1
          restartPolicy: OnFailure
