apiVersion: ENC[AES256_GCM,data:fGY=,iv:8Oc9lvVhCDZIzXbtjDn7qZpUkMP5zI/Bpx96Znvjzhk=,tag:QuJNsk0K/oDRhCwv5EjEWg==,type:str]
kind: ENC[AES256_GCM,data:tGF+BWL6,iv:oR7LcISQX0dOAp2/pdspfNiMtLty/lc1TVy8S75HFcs=,tag:qZVxL/hTmDUU6cQE4DCBFA==,type:str]
metadata:
    namespace: ENC[AES256_GCM,data:z5Pt96JMCSZAv0F0ASM=,iv:LLG2ldZ/eIFXCfXf0+yjKftoR4W3kM4vpUzjRi6CjCw=,tag:hDRlTEm5iHdL8WmPRZIFbw==,type:str]
    name: ENC[AES256_GCM,data:VVV0DuUtImiR+VAewkvUuSk=,iv:A7l0aZrKPEejmvm731dbMYl7UNWWjIyUErkMUJFCqeY=,tag:uccbxdbG26d2NzZCznuXJQ==,type:str]
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Jp8Ru9+SZnI=,iv:goK6T+0r0X/x8Ra7W3TJ8xeJsAfTyQJmLah+UdkNfBs=,tag:Ym6TV/RYLxZBiZn+kO87YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pnylf26lyq72vfvrjd2w4yx9juu0rv4mh6n4htvswjh5aqktt33qku8uas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb05BUkFtdWNySXhybGNu
            eExySUZGdTNaZnh1R1dZTEVXaitaeHRkRkQwClNVRzAxYUZSQjEzQnRGS05OWkhi
            Qm1pUklVMVVqSTdOTmNZQUN1eEI3UjQKLS0tIC9KOE50TmhVTEhiWHh4KzF2YjV2
            TFlNVEVXMnpiaHE5b3lvUFI2UkNBWHcKpufLFEH9w5AJVKQOOdf1XTKluMFjCJaj
            lpOTqhVlYhO4VrdZ8ssFHcXyiZa5EI1ye/oDxNQbaRsapR20wIDAmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-21T10:18:28Z"
    mac: ENC[AES256_GCM,data:bAfBBfbVHgN/0Oi9iZI6vOoKMO18cRnQLtI4hxZNr74FiaeDImsyrHU+M0P0nciHw/XGTP174ZnFZor8RKeuKBex5JH6JJrKlKpATb3kAG399sfKZhyxHLOTqUd4kKyRRvTr0VkLJPZJTLJcJ0mHmtegNEGq8yuklOXjJY9UFGU=,iv:HSjGka6YDbe8sMK6iWnV75JJ2d4xPU0VFSD5gOxkozE=,tag:WdlBEoQ3k4F9QhbNquAM4w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
